### ISSUE TITLE
Scoop search command improvement

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Ash258/Scoop-Core#169] opened 2021-06-12 12:01 UTC
Would be nice if scoop search would just grepsearch the index for keyphrases or search a kind of index instead of every time searching the buckets that ones have, this way the seach command would be much, much faster.

The more buckets one has the longer the scoop search takes. After every scoop update * the index would be updated with new stuff.

**Comment by Ash258** [comment] 2021-06-12 12:19
Duplicate of lukesampson/scoop#4239

**Closed by Ash258** 2021-06-12 12:19 UTC
Labels: enhancement
