### ISSUE TITLE
Scoop checkup fixable warnings not fixing?

### ISSUE THREAD

**Issue by M-FeD** [Ash258/Scoop-Core#131] opened 2021-03-24 21:58 UTC
- **Branch**: 
- **Powershell Version**: 

PS C:\Users\mfed\Documents\WindowsPowerShell> scoop checkup
WARN  Windows Defender may slow down or disrupt installs with realtime scanning.
Fixable with running following command in elevated prompt: 
Add-MpPreference -ExclusionPath 'C:\Users\mfed\scoop'
WARN  Windows Defender may slow down or disrupt installs with realtime scanning.
Fixable with running following command in elevated prompt:
Add-MpPreference -ExclusionPath 'C:\ProgramData\scoop'
WARN
WARN  Found 2 potential problems.

![image](https://user-images.githubusercontent.com/31779182/112389020-f32dcb80-8ceb-11eb-9a5e-fa335bd312ca.png)

Despite running those two commands in an administrator powershell prompt, and even restarting my computer these warnings still show up when running `scoop checkup`

**Comment by Ash258** [comment] 2021-03-25 02:04
Duplicate of lukesampson/scoop#4098

Next time you will open issue without providing all required information or duplicating upstream issue you will be blocked.

**Closed by Ash258** 2021-03-25 02:04 UTC
Labels: bug
